services:
  postgres:
    container_name: postgres
    image: postgres:16.8-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schema-postgresql.sql:/docker-entrypoint-initdb.d/init.sql